### PR TITLE
BadSecret + emergencyContact v1

### PR DESCRIPTION
**Pull request by johnhbenetech**
PNG and SVG v1 for BadSecret Icon

### CODE REVIEW

**Comment by razetime** [comment]
Looks nice!

**Comment by simonv3** [comment]
@johnhbenetech Thanks for doing this! In the future, can you include screenshots of the images in the PR? That way it's a bit easier to review. 

By the way cc @bnvk - this was something you were kind of leading :)

**Comment by bnvk** [comment]
@johnhbenetech thanks for the work- rad to meet last week :)

@razetime @simonv3 thanks for stewarding something I kind of started / was leading. I hope to finish it up at some point + will respond faster next time!

**Comment by johnhbenetech** [comment]
@bnvk Nice to meet you as well! This seems like low hanging fruit for me, so i'll keep transferring sketches to SVG as I have freetime.

**Comment by simonv3** [comment]
@bnvk That wasn't at all a reprimand! Just thought you'd be interested.

**Pull request merged**
