### PR TITLE
Added Covid Icons

### PR DESCRIPTION
**Pull request by hqrshguptq**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hi @hqrshguptq thanks for your contribution, but we don’t really maintain this repository anymore as there are many good existing open source icon platforms out there, the main one being https://thenounproject.com – we recommend uploading your icons there instead.

@ei8fdb @Erioldoesdesign @cameralibre @evalica @elioqoshi @perriefidelis al what do you think? I would recommend we lock/archive this repository to instead focus on being a hub for linking to these platforms as opposed to needing to curate for ourselves. (Similar for our "fonts" repo and others.)

**Comment by Erioldoesdesign** [comment]
Agreed @jancborchardt there are lots of free/open icon projects out there that are way more used/accessible and pointing towards those is super useful. I think these might be the ones from biorender.com?

@hqrshguptq thank you for your interest and contribution though! The COVID icons are super important and if you felt like writing an article about them and how you've used/found them or some text for a wiki and providing a link, there's definitely space for that kind of contribution on the opensourcedesign.net webpage

**Comment by ei8fdb** [comment]
> Hi @hqrshguptq thanks for your contribution, but we don’t really maintain this repository anymore as there are many good existing open source icon platforms out there, the main one being https://thenounproject.com – we recommend uploading your icons there instead.

I recently found https://feathericons.com/ (with a GH repo) which is another repo of nice, simple icons. @hqrshguptq either of those would help you get more exposure for the icons you've created.

> @ei8fdb @Erioldoesdesign @cameralibre @evalica @elioqoshi @perriefidelis al what do you think? I would recommend we lock/archive this repository to instead focus on being a hub for linking to these platforms as opposed to needing to curate for ourselves. (Similar for our "fonts" repo and others.)

Yes this makes sense. Good idea. I was looking through the icons this morning and wasn't sure what to do about them.

**Comment by hqrshguptq** [comment]
> @hqrshguptq thank you for your interest and contribution though! The COVID icons are super important and if you felt like writing an article about them and how you've used/found them or some text for a wiki and providing a link, there's definitely space for that kind of contribution on the opensourcedesign.net webpage

Hey @erioldoesdesign , sure. Please suggest me how could I just put up a blog about it :)
Thanks

**Comment by Erioldoesdesign** [comment]
@hqrshguptq if you take a look at https://opensourcedesign.net/articles/ and see ho we write articles, maybe this one is a good example: https://opensourcedesign.net/open-source/communities/collaboration/tools/design/2017/03/27/osd-needs-better-collaboration-tools.html

and if you want to write about how icons in general or covid icons specifically are important for open source designers etc. that'd be awesome. Have a go and see what you think :)

**Comment by hqrshguptq** [comment]
@Erioldoesdesign Cool, I will just draft an article and would mention it here soon. So, that It could be evaluated and then the article could be published after evaluation. 
Thanks, also let me know of more such tasks you guys are solving on day-to-day basis.

**Comment by hqrshguptq** [comment]
> and if you want to write about how icons in general or covid icons specifically are important for open source designers etc. that'd be awesome. Have a go and see what you think :)

Hi @Erioldoesdesign @everyone , Do Check this: 
https://docs.google.com/document/d/1rYYc_Latkc0xN8jHuGdzIk924nlqqhEQk9lk8JXb78k/edit?usp=sharing .
It's just a brief still, up for any suggestions.. thanks.

**Comment by hqrshguptq** [comment]
Also, regarding this if someone can help.. how to become a member. Thanks!
Screenshot 2020-08-17 at 12 56 52 AM

**Comment by Erioldoesdesign** [comment]
> Also, regarding this if someone can help.. how to become a member. Thanks!
> Screenshot 2020-08-17 at 12 56 52 AM

Sorted! added you as a member to the open source design team but didn't assign you a particular city/country :)

**Comment by hqrshguptq** [comment]
Yes, thanks. Btw, I belong to New Delhi,India. Also Granted edit permission on the Google Docs..

**Comment by hqrshguptq** [comment]
Hi all, @Erioldoesdesign 
Please look over the below PR if you just missed it in any case.. :) https://github.com/opensourcedesign/opensourcedesign.github.io/pull/297

**Pull request closed without merging**
